<?php
/**
 * A repeating group of fields — social links, services, team members.
 *
 * The rows live in one setting as a list of associative arrays. A hidden
 * input holds the JSON the Customizer saves; the visible fields only feed it,
 * so there is a single source of truth and no partial-save states.
 *
 * Row markup is generated by one method, used both for the rows rendered on
 * load and for the template the Add button clones, so the two cannot drift.
 *
 * @package Colorlib
 */

defined( 'ABSPATH' ) || exit;

if ( ! class_exists( 'Colorlib_Control_Repeater' ) ) {

	/**
	 * Class Colorlib_Control_Repeater
	 */
	class Colorlib_Control_Repeater extends WP_Customize_Control {

		/**
		 * @var string
		 */
		public $type = 'colorlib-repeater';

		/**
		 * Field key => field definition ( label, type, default, choices ).
		 *
		 * @var array
		 */
		public $fields = array();

		/**
		 * How to title a collapsed row.
		 *
		 * array( 'type' => 'field', 'field' => 'title' ) takes the title from
		 * that field's value; array( 'type' => 'text', 'value' => '…' ) is fixed.
		 *
		 * @var array
		 */
		public $row_label = array();

		/**
		 * Label for the add button.
		 *
		 * @var string
		 */
		public $button_label = '';

		/**
		 * The rows, always a list of arrays.
		 *
		 * @return array
		 */
		private function rows() {
			$value = $this->value();

			if ( ! is_array( $value ) ) {
				$decoded = json_decode( $value, true );
				$value   = is_array( $decoded ) ? $decoded : array();
			}

			$rows = array();
			foreach ( $value as $row ) {
				if ( ! empty( $row ) ) {
					$rows[] = (array) $row;
				}
			}

			return $rows;
		}

		/**
		 * The text shown on a collapsed row.
		 *
		 * @param array $row   Row values.
		 * @param int   $index Row position.
		 * @return string
		 */
		private function row_title( array $row, $index ) {
			$type = isset( $this->row_label['type'] ) ? $this->row_label['type'] : '';

			if ( 'field' === $type && ! empty( $this->row_label['field'] ) ) {
				$key = $this->row_label['field'];
				if ( ! empty( $row[ $key ] ) && is_scalar( $row[ $key ] ) ) {
					return (string) $row[ $key ];
				}
			}

			if ( 'text' === $type && ! empty( $this->row_label['value'] ) ) {
				return (string) $this->row_label['value'];
			}

			/* translators: %s: row number. */
			return sprintf( __( 'Item %s', 'colorlib' ), number_format_i18n( $index + 1 ) );
		}

		/**
		 * One field inside a row.
		 *
		 * @param string $key      Field key.
		 * @param array  $field    Field definition.
		 * @param mixed  $value    Current value.
		 */
		private function render_field( $key, array $field, $value ) {
			$type  = isset( $field['type'] ) ? Colorlib_Customizer::normalize_type( $field['type'] ) : 'text';
			$label = isset( $field['label'] ) ? $field['label'] : '';
			?>
			<label class="colorlib-repeater__field">
				<?php if ( '' !== $label ) : ?>
					<span class="colorlib-repeater__field-label"><?php echo esc_html( $label ); ?></span>
				<?php endif; ?>

				<?php
				switch ( $type ) {
					case 'textarea':
					case 'colorlib-text-editor':
						?>
						<textarea rows="4" class="widefat" data-field="<?php echo esc_attr( $key ); ?>"><?php echo esc_textarea( $value ); ?></textarea>
						<?php
						break;

					case 'select':
						?>
						<select class="widefat" data-field="<?php echo esc_attr( $key ); ?>">
							<?php
							$choices = isset( $field['choices'] ) ? (array) $field['choices'] : array();
							foreach ( $choices as $choice_value => $choice_label ) :
								?>
								<option value="<?php echo esc_attr( $choice_value ); ?>" <?php selected( (string) $choice_value, (string) $value ); ?>>
									<?php echo esc_html( $choice_label ); ?>
								</option>
							<?php endforeach; ?>
						</select>
						<?php
						break;

					case 'checkbox':
					case 'colorlib-toggle':
						?>
						<input type="checkbox" value="1" data-field="<?php echo esc_attr( $key ); ?>" <?php checked( (bool) $value ); ?> />
						<?php
						break;

					case 'colorlib-color-picker':
						?>
						<input type="text" class="widefat colorlib-repeater__color" data-field="<?php echo esc_attr( $key ); ?>" value="<?php echo esc_attr( $value ); ?>" />
						<?php
						break;

					case 'colorlib-icon-picker':
						?>
						<span class="colorlib-repeater__icon">
							<i class="colorlib-repeater__icon-preview <?php echo esc_attr( $value ); ?>" aria-hidden="true"></i>
							<input type="text" class="widefat" data-field="<?php echo esc_attr( $key ); ?>" value="<?php echo esc_attr( $value ); ?>" placeholder="fa-brands fa-twitter" />
						</span>
						<?php
						break;

					case 'image':
					case 'colorlib-image':
					case 'upload':
					case 'colorlib-upload':
						?>
						<span class="colorlib-repeater__media">
							<input type="text" class="widefat" data-field="<?php echo esc_attr( $key ); ?>" value="<?php echo esc_attr( $value ); ?>" />
							<button type="button" class="button colorlib-repeater__media-pick"><?php esc_html_e( 'Select image', 'colorlib' ); ?></button>
						</span>
						<?php
						break;

					default:
						?>
						<input type="<?php echo esc_attr( 'url' === $type ? 'url' : 'text' ); ?>" class="widefat" data-field="<?php echo esc_attr( $key ); ?>" value="<?php echo esc_attr( $value ); ?>" />
						<?php
				}
				?>
			</label>
			<?php
		}

		/**
		 * One row.
		 *
		 * @param int|string $index Row position, or __INDEX__ for the template.
		 * @param array      $row   Row values.
		 */
		private function render_row( $index, array $row ) {
			$numeric = is_numeric( $index ) ? (int) $index : 0;
			?>
			<li class="colorlib-repeater__row" data-index="<?php echo esc_attr( $index ); ?>">
				<div class="colorlib-repeater__row-head">
					<button type="button" class="colorlib-repeater__toggle" aria-expanded="false">
						<span class="colorlib-repeater__row-title"><?php echo esc_html( $this->row_title( $row, $numeric ) ); ?></span>
					</button>
					<span class="colorlib-repeater__row-actions">
						<button type="button" class="colorlib-repeater__move" data-dir="up" title="<?php esc_attr_e( 'Move up', 'colorlib' ); ?>">&uarr;</button>
						<button type="button" class="colorlib-repeater__move" data-dir="down" title="<?php esc_attr_e( 'Move down', 'colorlib' ); ?>">&darr;</button>
						<button type="button" class="colorlib-repeater__remove" title="<?php esc_attr_e( 'Remove', 'colorlib' ); ?>">&times;</button>
					</span>
				</div>
				<div class="colorlib-repeater__row-body" hidden>
					<?php
					foreach ( $this->fields as $key => $field ) {
						$value = isset( $row[ $key ] ) ? $row[ $key ] : ( isset( $field['default'] ) ? $field['default'] : '' );
						$this->render_field( $key, (array) $field, $value );
					}
					?>
				</div>
			</li>
			<?php
		}

		/**
		 * Render.
		 */
		public function render_content() {
			if ( empty( $this->fields ) ) {
				return;
			}

			$rows   = $this->rows();
			$button = ! empty( $this->button_label ) ? $this->button_label : __( 'Add item', 'colorlib' );

			// The template row, with defaults and a placeholder index that the
			// script swaps for the real position.
			$defaults = array();
			foreach ( $this->fields as $key => $field ) {
				$defaults[ $key ] = isset( $field['default'] ) ? $field['default'] : '';
			}

			ob_start();
			$this->render_row( '__INDEX__', $defaults );
			$template = ob_get_clean();
			?>
			<?php
			// The script retitles a collapsed row as you type in this field.
			$label_field = ( isset( $this->row_label['type'] ) && 'field' === $this->row_label['type'] && ! empty( $this->row_label['field'] ) )
				? $this->row_label['field']
				: '';
			?>
			<div
				class="colorlib-repeater"
				data-setting="<?php echo esc_attr( $this->id ); ?>"
				data-row-label-field="<?php echo esc_attr( $label_field ); ?>"
			>
				<span class="customize-control-title"><?php echo esc_html( $this->label ); ?></span>
				<?php if ( ! empty( $this->description ) ) : ?>
					<span class="description customize-control-description"><?php echo wp_kses_post( $this->description ); ?></span>
				<?php endif; ?>

				<input type="hidden" class="colorlib-repeater__value" <?php $this->link(); ?> />

				<ul class="colorlib-repeater__rows">
					<?php foreach ( $rows as $index => $row ) : ?>
						<?php $this->render_row( $index, $row ); ?>
					<?php endforeach; ?>
				</ul>

				<button type="button" class="button colorlib-repeater__add"><?php echo esc_html( $button ); ?></button>

				<script type="text/html" class="colorlib-repeater__template">
					<?php echo $template; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- markup built above from escaped parts. ?>
				</script>
			</div>
			<?php
		}
	}
}
